### ISSUE TITLE
Unity SDK stops working after domain verification

### ISSUE THREAD

**Issue by ali-t-gw** [reown-com/reown-dotnet#18]
I have created total 3 cloud projects. 2 of them just domain verification started. 1 is domain is verified. The project stopped working after domain verification. Now I have 3 projects cannot connect websocket.

> 11-19 21:30:53.317 16752 16992 E Unity   : IOException: Could not establish connection
11-19 21:30:53.317 16752 16992 E Unity   :   at Reown.Core.Controllers.Relayer.ToEstablishConnection (System.Threading.CancellationToken cancellationToken) [0x00000] in <00000000000000000000000000000000>:0 
11-19 21:30:53.317 16752 16992 E Unity   :   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <00000000000000000000000000000000>:0 
11-19 21:30:53.317 16752 16992 E Unity   :   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run () [0x00000] in <00000000000000000000000000000000>:0 
11-19 21:30:53.317 16752 16992 E Unity   :   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction (System.Action action, System.Boolean allowInlining, System.Threading.Tasks.Task& currentTask) [0x00000] in <00000000000000000000000000000000>:0 
11-19 21:30:53.317 16752 16992 E Unity   :   at System.Threading.Tasks.Task.FinishContinuations () [0x00000] in <00000000000000000000000000000000>:0 
11-19 21:30:53.317 16752 16992 E Unity   :   at System.Threading.Tasks.Task`1[TResult].TrySetResult (TResult result) [0x00000] in <00000000000000000000
11-19 21:30:53.343  1014 17262 I sensors-hal: handle_sns_client_event:541, [0][1872] accel_sample [ 0.782,  0.408,  9.810] 736577172626571

> 11-19 21:30:58.682 16752 17339 E Unity   : WebSocketException: Unable to connect to the remote server
11-19 21:30:58.682 16752 17339 E Unity   :   at Reown.Core.Network.JsonRpcProvider.Connect (Reown.Core.Network.IJsonRpcConnection connection) [0x00000] in <00000000000000000000000000000000>:0 
11-19 21:30:58.682 16752 17339 E Unity   :   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <00000000000000000000000000000000>:0 
11-19 21:30:58.682 16752 17339 E Unity   :   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run () [0x00000] in <00000000000000000000000000000000>:0 
11-19 21:30:58.682 16752 17339 E Unity   :   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00000] in <00000000000000000000000000000000>:0 
11-19 21:30:58.682 16752 17339 E Unity   : --- End of stack trace from previous location where exception was thrown ---
11-19 21:30:58.682 16752 17339 E Unity   : 
11-19 21:30:58.682 16752 17339 E Unity   :   at Reown.Core.Network.JsonRpcProvider.Request[T,TR] (Reown.Core.Network.IRequestArguments`1[T] requestArgs, System.Object context) [0x00000] in <00000000000000000000000000000000>:0 
11-19 21:30:58.682 16752 17339 E Unity   :   at System.Threading.ExecutionContext.RunInternal (System.Thre

I have created 4th project. Only changed projectId, and websocket started working again. 

<img width="480" alt="image" src="https://github.com/user-attachments/assets/dfc28513-2832-46d3-ae9e-c5b62e21b518">

Unity Version 2022.3.22
AppKit: 
<img width="480" alt="image" src="https://github.com/user-attachments/assets/74f68a79-e034-4de1-b1d8-c67541aeaf5e">

**Comment by skibitsky** [comment]
Hello,

Have you tried connecting to a different Internet network? The error message looks like a generic connectivity issue.

Could you please share one of the project IDs so I can investigate further? It's not a sensitive value and is safe to share publicly.

**Comment by ali-t-gw** [comment]
> Hello,
> 
> Have you tried connecting to a different Internet network? The error message looks like a generic connectivity issue.
> 
> Could you please share one of the project IDs so I can investigate further? It's not a sensitive value and is safe to share publicly.

yes unfortunately this error happens after domain verification process on reown cloud. below image, the one was first project, then i started domain verification. verfied domain. suddenly project started to give that error. left is non-working with domain verification. right is working without domain verification. project builded with project id on the right immediate after the one on the left broken.

<img width="1308" alt="image" src="https://github.com/user-attachments/assets/7af73f2a-4da5-4e9a-aeb2-7ae2c96c58d7">

**Comment by skibitsky** [comment]
Hello @ali-t-gw,

A potential solution was implemented in version 1.1.0. Could you please update to this version and verify whether the issue still occurs?

**Comment by ali-t-gw** [comment]
> Hello @ali-t-gw,
> 
> A potential solution was implemented in version 1.1.0. Could you please update to this version and verify whether the issue still occurs?

Hi, Old project IDs started working after updating 1.1.1 via the package manager. Thanks
