### ISSUE TITLE
JSON RPC ERROR: Gas Estimates error; Random

### ISSUE THREAD

**Issue by Umair72Raza** [reown-com/reown-dotnet#20]
Hello, I need help in my dApp where I am using Reown appkit with Unity and polygon amoy testnet to deploy and interact with contracts.

I am new to blockchain and using Reown Appkit to interact with ERC 20 and ERC1155 contracts. I am connecting to my account using the wallet connect feature from the Reown Appkit Modal to connect my mobile wallet to the unity app. In one of my code chunk, I am trying to mint ERC 20 token by giving the Polygon Amoy Testnet currency. The transaction fails randomly. It gets successful like 4 in 10 times. I am unable to observe the test case because the error and success are random. The mobile wallet app crashes and in the logs I see JSON RPC error or gas estimate failed. 
I am using Reown App-kit and deployed my contracts on the polygon amoy testnet that has chainId eip:80002. 

`
await AppKit.InitializeAsync(new AppKitConfig
{
    projectId = "your-project-id", 
    metadataUrl = "https://metadata-url.com", 

    supportedChains = new[]
    {
        ChainConstants.Chains.Polygon,

        new Chain(ChainConstants.Namespaces.Evm,
            chainReference: "80002",
            name: "Polygon Amoy",
            nativeCurrency: new Currency("Pol", "POL", 18),
            blockExplorer: new BlockExplorer("Oklink", "https://www.oklink.com/amoy"),
            rpcUrl: "https://rpc-amoy.polygon.technology",
            isTestnet: true,
            imageUrl: $"https://api.web3modal.com/public/getAssetImage/your-image-id",
            viemName: "polygonAmoyTestnet"
        )
    }
});

`

here is the function hashes of the contract:

`{
	"dd62ed3e": "allowance(address,address)",
	"095ea7b3": "approve(address,uint256)",
	"70a08231": "balanceOf(address)",
	"313ce567": "decimals()",
	"4b94f50e": "getTokenPrice()",
	"40c10f19": "mint(address,uint256)",
	"06fdde03": "name()",
	"8da5cb5b": "owner()",
	"715018a6": "renounceOwnership()",
	"6a61e5fc": "setTokenPrice(uint256)",
	"95d89b41": "symbol()",
	"7ff9b596": "tokenPrice()",
	"18160ddd": "totalSupply()",
	"a9059cbb": "transfer(address,uint256)",
	"23b872dd": "transferFrom(address,address,uint256)",
	"f2fde38b": "transferOwnership(address)"
}`

Here is the code:

`
// mint mr token using matics
[ContextMenu("MintTokensWithMatic")]
    private async void MintTokensWithMatic()
    {
        // Get the user's account information
        Account account = await AppKit.GetAccountAsync();
        string recipientAddress = account.Address;

        // Set the amount of MR tokens to mint (adjust this to the desired number of tokens)
        BigInteger mintAmount = new BigInteger(1e18); // Mint 1 MR token, scaled to 18 decimals

        // Hardcoded price: 1 MATIC per token
        BigInteger maticPricePerToken = new BigInteger(1e18); // 1 MATIC in wei

        // Calculate the total MATIC needed (1 MATIC per token)
        BigInteger totalMaticToSend = mintAmount * maticPricePerToken / new BigInteger(1e18); // Adjust for scaling

        // ABI encoding for "mint(address to, uint256 amount)"
        var functionSignature = "0x40c10f19";
        string recipientParam = recipientAddress.Substring(2).PadLeft(64, '0'); // Pad address to 32 bytes
        string amountParam = mintAmount.ToString("x").PadLeft(64, '0');         // Pad amount to 32 bytes

        // Concatenate function signature and parameters
        string data = functionSignature + recipientParam + amountParam;
        try
        {
            // Send the transaction to mint tokens, including 1 MATIC in wei
            var transactionHash = await AppKit.Evm.SendTransactionAsync(contractAddressMRToken, totalMaticToSend, data);
            
            Debug.Log("Mint transaction with 1 MATIC sent, transaction hash: " + transactionHash);
        }
        catch (Exception ex)
        {
            Debug.LogError("Failed to mint tokens: " + ex.Message);
        }
    }
`

**Comment by skibitsky** [comment]
Hi!

You don't need to build data from the method signature manually. Instead you can call contract methods directly with the contract ABI. Docs with example: https://docs.reown.com/appkit/unity/core/usage#send-erc20-token

**Comment by Umair72Raza** [comment]
Now, I am getting this error

ReownNetworkException: Internal JSON-RPC error.
Reown.Sign.Engine.Request[T,TR] (System.String topic, T data, System.String chainId, System.Nullable`1[T] expiry) (at ./mailto:library/packagecache/com.reown.sign@1.0.1/runtime/engine.cs:734)
Reown.Sign.Nethereum.ReownSignServiceCore.SendTransactionAsyncCore (Nethereum.RPC.Eth.DTOs.TransactionInput transaction) (at ./mailto:library/packagecache/com.reown.sign.nethereum@1.0.1/runtime/reownsignservicecore.cs:55)
.....

This is my updated code:

`

 [ContextMenu("MintTokensWithMatic")]
    private async void MintTokensWithMatic()
    {
        // Get the user's account information
        Account account = await AppKit.GetAccountAsync();
        string recipientAddress = account.Address;

        // Set the amount of MR tokens to mint (adjust this to the desired number of tokens)
        BigInteger mintAmount = new BigInteger(1e18); // Mint 1 MR token, scaled to 18 decimals

        // Hardcoded price: 1 MATIC per token
        BigInteger maticPricePerToken = new BigInteger(1e18); // 1 MATIC in wei

        // Calculate the total MATIC needed (1 MATIC per token)
        BigInteger totalMaticToSend = mintAmount * maticPricePerToken / new BigInteger(1e18); // Adjust for scaling

        // ABI encoding for "mint(address to, uint256 amount)"
        var functionSignature = "0x40c10f19";
        string recipientParam = recipientAddress.Substring(2).PadLeft(64, '0'); // Pad address to 32 bytes
        string amountParam = mintAmount.ToString("x").PadLeft(64, '0');         // Pad amount to 32 bytes

        // Concatenate function signature and parameters
        string data = functionSignature + recipientParam + amountParam;
        
        
        ////////////////////////////////////////////////////////////////////////

        BigInteger amount = new BigInteger(1e18);


        var arguments = new object[]
        {
            recipientAddress,
            totalMaticToSend
        };
        var result = await AppKit.Evm.WriteContractAsync(contractAddressMRToken, PayableMRTokenABI ,"mint",  amount ,arguments);
        Debug.Log("<color=yellow> Result </color>" + result);
        ////////////////////////////////////////////////////////////////////////
            }


`

**Comment by Umair72Raza** [comment]
I have attached the files with abi and contract 
[MRTokenABI.txt](https://github.com/user-attachments/files/17866642/MRTokenABI.txt)
[MRTokenContract.txt](https://github.com/user-attachments/files/17866643/MRTokenContract.txt)

**Comment by skibitsky** [comment]
@Umair72Raza do you mind sharing an address of deployed contract please?

**Comment by Umair72Raza** [comment]
The deployed contract address:

0x237A87B2c6e55cC0FAB2ec411016f23F1B50D7d3

**Comment by Umair72Raza** [comment]
I am still waiting for the resolution of the JSON-RPC error

**Comment by skibitsky** [comment]
Hey @Umair72Raza, 

Apologise for the delay, I'm not active here on weekends :) 

You call `WriteContractAsync` with 5 arguments, so the following overload is used
```csharp
public Task<string> WriteContractAsync(
            string contractAddress,
            string contractAbi,
            string methodName,
            BigInteger gas = default,
            params object[] arguments
        );
```

Let's go over the code you provided:
```csharp
// The `amount` is set to 1 × 10¹⁸
BigInteger amount = new BigInteger(1e18);

// Arguments for `function mint(address to, uint256 amount)`, all good here
var arguments = new object[]
{
    recipientAddress,
    totalMaticToSend
};
var result = await AppKit.Evm.WriteContractAsync(
        contractAddressMRToken, 
        PayableMRTokenABI ,
        "mint",  
        amount , // ⚠️ this is is an optional _gas_ amount value, you set it to `amount`
        arguments // arguments for `mint` function
);
```

The `amount` value in your case is 1 × 10¹⁸ which is too much. The `value` argument is also missing. The `mint` function in your contract is `payable` and it checks if you send enough POL along with the function call to buy an `amount` of MR token.

You can estimate gas amount and use `value` field like so:
```csharp
// Same arguments as before
var arguments = new object[]
{
    recipientAddress,
    totalMaticToSend
};

// Estimate gas amount for `mint` with given arguments. 
// The `0` here is the `value`, an amount of POL
var gasAmount = await AppKit.Evm.EstimateGasAsync(
        contractAddressMRToken, 
        PayableMRTokenABI, 
        "mint", 
        totalMaticToSend, // an amount of POL we send to the contract (because `mint` is payable)
        arguments
);

var result = await AppKit.Evm.WriteContractAsync(
        contractAddressMRToken, 
        PayableMRTokenABI ,
        "mint",  
        value: totalMaticToSend, // an amount of POL we send to the contract
        gas: gasAmount , // estimated gas amount
        arguments // arguments for `mint` function
);
```

My successful transaction hash: [0xdfec94647713446dacebfe5575805113ab9e56e45915c5aacb7a8ae86458672a](https://www.oklink.com/amoy/tx/0xdfec94647713446dacebfe5575805113ab9e56e45915c5aacb7a8ae86458672a)

**Comment by Mohsin-Raza-GenITeam** [comment]
I am also working with @Umair72Raza.
I am trying to call the EstimateGasAsync but it is not available. the list of available methods of this AppKit.Evm are

![image](https://github.com/user-attachments/assets/b51ccbd3-7cb9-49fe-b89f-de429073dd74)


I am unable to see this method and if I write this method, IDE makes it red saying cannot resolve "EstimateGasAsync".

If it is a version issue:
here is the versions of my packages
![image](https://github.com/user-attachments/assets/373000cd-0da5-4f37-9eaf-15806eecc5a8)

**Comment by Umair72Raza** [comment]
@skibitsky , Mohsin is working with me on the same problem since thursday

**Comment by skibitsky** [comment]
Please update to v1.1.0

**Comment by Umair72Raza** [comment]
I am testing your implementation. I get 3-4 transactions successfully and then it fails many times. The transactions were made one after another within the time period 2-3 minutes. 
When the transactions fail, the network fee that I see in my mobile wallet is too low. Is it some issue from our development end because now we are even sending the gas fee along with it

**Comment by Umair72Raza** [comment]
@skibitsky 
The error I see in console:

Failed to mint tokens: Internal JSON-RPC error.
UnityEngine.Debug:LogError (object)
ReownInitializer/<MintTokensWithMatic>d__23:MoveNext () (at Assets/ReownInitializer.cs:369)
UnityEngine.UnitySynchronizationContext:ExecuteTasks ()


Sometimes failed one have the network fee of "0.000059" and the image with network fee of 0.000961 has failed.

On the app I see Internal JSON-RPC Error and the app crashes

Images:
![fail](https://github.com/user-attachments/assets/657bb529-0233-43af-8f4d-25d2cffc0d77)
![Pass1](https://github.com/user-attachments/assets/c527e868-9ed5-4c9d-863e-75f3ea9d576d)
![Pass2](https://github.com/user-attachments/assets/a7785232-e7cb-4ec5-a9e5-fd98dd6c9514)

**Comment by Umair72Raza** [comment]
Hi @skibitsky 
Another off the topic question is that do we have the feature to connect using Reown Appkit wallet connect feature using Solana in Unity?

**Comment by skibitsky** [comment]
> connect feature using Solana in Unity

Not yet. But it's on the roadmap along with some other non-EVM chains.
