### ISSUE TITLE
[bug] Editing supported chains and wallets not working on AppKit in WebGL build in Unity

### ISSUE THREAD

**Issue by SantaDud** [reown-com/reown-dotnet#4]
### Link to minimal reproducible example
**N/A**

### Summary
I'm currently trying to edit my supported chains and wallets on AppKit. The problem is that the changes work in the editor but not in the WebGL build.

![Screenshot 2024-10-01 165730](https://github.com/user-attachments/assets/9b37a7d2-e3de-4981-a89e-2128cdd1b251)
![Screenshot 2024-10-01 165754](https://github.com/user-attachments/assets/02e3d189-1631-4fa2-aa76-baf24050b43b)

### Code
`public class AppkitManager : MonoBehaviour
    {
        private const string CHAIN_IMAGE_URL = "https://api.web3modal.com/public/getAssetImage";
        
        private async void Start()
        {
            await AppKit.InitializeAsync(new AppKitConfig(projectId: "07c7fe157897a85c6c8b4b70d5e7e9f5",
                new Metadata(name: "Landverse", description: "Landverse Telegram App", url: "https://dev.landverseminiapp.com/",
                    iconUrl: "https://blog.sei.io/content/images/2022/08/Sei-logo-only-6.png"))
            {
                includedWalletIds = new []
                {
                    "c57ca95b47569778a828d19178114f4db188b89b763c899ba0be274e97267d96",
                },
                
                supportedChains = new []
                {
                    ChainConstants.Chains.Ethereum, 
                    ChainConstants.Chains.Polygon, 
                    ChainConstants.Chains.Ronin, 
                    
                    new Chain(ChainConstants.Namespaces.Evm,
                        "713715",
                        "Sei Devnet",
                        new Currency("Sei", "SEI", 18),
                        new BlockExplorer("Seitrace", "https://seitrace.com"),
                        "https://evm-rpc-arctic-1.sei-apis.com",
                        true,
                        $"{CHAIN_IMAGE_URL}/692ed6ba-e569-459a-556a-776476829e00"),
                    
                    new Chain(ChainConstants.Namespaces.Evm,
                        "1329",
                        "Sei Network",
                        new Currency("Sei", "SEI", 18),
                        new BlockExplorer("Seitrace", "https://seitrace.com"),
                        "https://evm-rpc.sei-apis.com/",
                        false,
                        $"{CHAIN_IMAGE_URL}/692ed6ba-e569-459a-556a-776476829e00"),
                }
            });
        }
        
        public void OpenAppKitModal()
        {
            if (!AppKit.IsInitialized)
            {
                return;
            }
            
            AppKit.OpenModal();
        }
    }`

### Additional Details
The version of Unity is 2023.2.7f1. Platform is WebGL. Managed stripping level set to Minimal.

**Comment by skibitsky** [comment]
Hello,

Thank you for opening the issue 🙏 

I can confirm that some of the appkit configurations aren't properly propagated to the WebGL.

**Comment by skibitsky** [comment]
Fixed in v1.0.1
