### ISSUE TITLE
Unity Error: README.md has no meta file and can not build project

### ISSUE THREAD

**Issue by talha-trili** [reown-com/reown-dotnet#9]
Appkit.Unity package is missing a meta file which is **preventing building the project**.
<img width="581" alt="image" src="https://github.com/user-attachments/assets/dbcaeb39-fa09-497e-9180-72e93161c1bb">
<img width="255" alt="image" src="https://github.com/user-attachments/assets/3bddb2f9-4a75-4657-9c9e-e04c1b2a83e5">

### Workaround
As a temporary solution, this error can be fixed by deleting README.md file but since its a unity package meaning its under cache folder, any change made to a package will revert to its original state when unity re-starts.

### Suggested Solution
Push the missing README.md.meta file and get a new release.

**Comment by skibitsky** [comment]
Hello,

Thank you for opening the issue! This error shouldn't block you from using the package, so you can ignore it for now. It will be fixed in the next release.

**Comment by skibitsky** [comment]
@talha-trili I cannot reproduce the issue with the v1.0.1, could you upgrade please?

**Comment by talha-trili** [comment]
Yes i can confirm this issue is fixed in 1.0.1, thanks for the help.
